# CAFA eval parameters

thresholding:
  mode: "per_class"
  grid: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3]
metrics:
  - fmax
  - pr_auc_micro
  - pr_auc_macro
dump:
  predictions_dir: outputs/preds/${now:%Y%m%d-%H%M%S}
  curves: true
