# configs/system/gcp.yaml

seed: 42
cudnn_deterministic: true        # stable results across runs
cudnn_benchmark: false           # keep false for determinism

# --- Compute / precision ---
device: cuda                     # "cuda"|"cpu"
precision: "bf16"                # "fp32"|"fp16"|"bf16"  (A100 → bf16, T4 → fp16/fp32)
amp: true                        # autocast mixed precision

# --- Data loading ---
num_workers: 8                   # set ~ (#vCPU / 2); override per VM
prefetch_factor: 2               # small to keep RAM sane
pin_memory: true
persistent_workers: true

# --- Paths (override these per project) ---
# Local cache inside VM instance; fast NVMe if available
local_cache_dir: /mnt/disks/nvme/cache

# Bucket for shared artifacts (read/write by all VMs)
gcs_bucket: gs://pf-agcn-cache        # << change me
gcs_artifacts: ${.gcs_bucket}/artifacts
gcs_datasets:  ${.gcs_bucket}/datasets
gcs_priors:    ${.gcs_bucket}/priors

# Canonical cache dir used by the rest of your configs
cache_dir: ${.local_cache_dir}

# --- Checkpointing & resume ---
save_dir: ${hydra:runtime.output_dir}  # hydra’s run dir on the VM
checkpoint_dir: ${.save_dir}/checkpoints
checkpoint_interval_epochs: 1          # save every N epochs (preemptible-safe)
resume: false                          # set true to auto-resume latest ckpt in dir

# --- MLflow (remote tracking + GCS artifact store) ---
mlflow:
  tracking_uri: http://<YOUR-MLFLOW-SERVER>:5000   # or "file:mlruns" for local
  experiment_name: pfagcn_gcp
  artifact_root: ${system.gcs_artifacts}           # keep artifacts in GCS

# --- DDP / multi-GPU (single node) ---
distributed:
  enabled: false                    # set true if you spin up multi-GPU VMs
  backend: nccl
  find_unused_parameters: false
  timeout_seconds: 1800

# --- Preemptible handling (best practices) ---
preemptible:
  enabled: true
  save_on_sigterm: true             # trainer should trap SIGTERM and save
  sigterm_grace_seconds: 30         # GCE sends ~30s warning on preemption

# --- Priors/embeddings build policy ---
rebuild_priors: false               # default: reuse cached .npz from GCS
rebuild_embeddings: false

# --- Logging cadence ---
log_every: 50                       # steps
val_every_epochs: 1

# --- Environment integration (optional, but handy) ---
env:
  GOOGLE_APPLICATION_CREDENTIALS: /etc/gcloud/key.json  # if using a service acct key
  MLFLOW_TRACKING_URI: ${system.mlflow.tracking_uri}

# --- Hydra runtime (puts each run under /mnt + timestamped dir) ---
hydra:
  run:
    dir: ${system.local_cache_dir}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${system.local_cache_dir}/sweeps/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S}_${hydra.job.num}

# --- Instance “presets” you can override on the CLI ---
# Examples: pick one at runtime: `system.gpu_preset=a100`
gpu_preset: a100
gpu_presets:
  t4:
    precision: "fp16"
    num_workers: 4
  a100:
    precision: "bf16"
    num_workers: 8
