# configs/system/local.yaml
# Baseline Hydra + runtime settings for workstation development.

seed: 42
cudnn_deterministic: true
cudnn_benchmark: false

# --- Compute / precision ---
device: auto
precision: "fp32"
amp: false

# --- Data loading ---
num_workers: 4
prefetch_factor: 2
pin_memory: false
persistent_workers: false

# --- Paths ---
cache_dir: /.cache/local
save_dir: 
checkpoint_dir: /checkpoints
checkpoint_interval_epochs: null
resume: false

# --- Experiment tracking ---
mlflow:
  tracking_uri: null
  experiment_name: pfagcn_local
  artifact_root: null

# --- Distributed setup ---
distributed:
  enabled: false
  backend: null
  find_unused_parameters: false
  timeout_seconds: 1800

# --- Preemptible handling ---
preemptible:
  enabled: false
  save_on_sigterm: false
  sigterm_grace_seconds: 0

# --- Priors/embeddings policy ---
rebuild_priors: false
rebuild_embeddings: false

# --- Logging cadence ---
log_every: 50
val_every_epochs: 1

# --- Environment thread caps ---
env:
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  NUMEXPR_NUM_THREADS: 8
  TORCH_NUM_THREADS: 8

# --- Hydra runtime ---
hydra:
  run:
    dir: /results/local//
  job:
    chdir: true
  sweep:
    dir: /results/local/sweeps/
    subdir: _


