# base PF-AGCN configuration.

task:
  num_functions: 2048
  vocab_size: 21
  pad_index: 0

model:
  seq_embeddings:
    cache_path: null
    feature_dim: 320
    seq_len: 512
    dtype: float32
  prot_prior:
    cache_path: null
    top_p_mass: 0.9
    temperature: 1.0
    symmetric: true
  go_prior:
    cache_path: null
    top_p_mass: 0.9
    temperature: 1.0
    symmetric: true
  dccn:
    channels: 128
    kernel_size: 3
    dilation: 2
    dropout: 0.1
  seq_gating:
    shared_dim: 256
    esm_dim: 320
    dccn_channels: 128
    attn_hidden: 256
    dropout: 0.1
  seq_final:
    metric_dim: 128
    graph_dim: 256
  adaptive_protein:
    feature_dim: 256
    attention_dim: 256
    steps: 3
    top_p_mass: 0.9
    temperature: 1.0
    dropout: 0.1
  adaptive_function:
    feature_dim: 256
    attention_dim: 256
    steps: 2
    top_p_mass: 0.9
    temperature: 1.0
    dropout: 0.1
  head:
    feature_dim: 256
    dropout: 0.1
  loss:
    name: bce_with_logits
    pos_weight: null
