# default config stack

defaults:
  - data: cafa
  - model: pf_agcn_base
  - train: train_default
  - eval: cafa
  - hpo: optuna_search
  - 
  - system: local
  - _self_

experiment_name: "pfagcn_dev"
resume: false