# default config stack

defaults:
  - data_config: cafa
  - task: pf_agcn
  - model: pf_agcn_base
  - train@_here_: train_default
  - eval: cafa
  - hpo: optuna_search
  - system: local
  - _self_

experiment_name: "pfagcn_dev"
resume: false

training: {}
optimizer: {}
scheduler: {}
data: {}
evaluation: {}

aspect: null

