# gcp_budget.yaml
# lightweight GCP spend plan for Optuna sweeps + core training.

project:
  name: pf-agcn-sweeps
  billing_account: placeholder-billing
  region: us-central1

assumptions:
  trial_hours: 2.0
  concurrent_trials: 4
  duration_weeks: 4
  currency: USD

compute_tiers:
  training_gpu:
    machine_type: n1-standard-8
    hourly_rate: 0.379
    accelerator: tesla_t4
    accelerator_rate: 0.35
    utilization: 0.7
  preprocessing_cpu:
    machine_type: n1-standard-4
    hourly_rate: 0.19
    utilization: 0.5

cost_projection:
  optuna_trials:
    total_hours: 128
    blended_rate: 0.729
    compute_cost: 93.31
  baseline_training:
    total_hours: 80
    blended_rate: 0.729
    compute_cost: 58.32
  storage:
    bucket_gb: 200
    storage_rate: 0.02
    monthly_cost: 4.0
  network:
    egress_gb: 100
    egress_rate: 0.12
    monthly_cost: 12.0
  monitoring_overhead: 25.0

budget_summary:
  monthly_cap: 600.0
  subtotal: 192.63
  contingency_multiplier: 1.15
  recommended_allocation: 221.52