# optuna_search.yaml
# optuna hyperparameter ranges + study policy.

study:
  name: pf_agcn_dev
  storage: sqlite:///results/optuna_dev.db
  direction: maximize
  sampler: tpe
  pruner: median
  n_trials: 60
  timeout_minutes: 720
  seed: 2025

search_space:
  optimizer.lr:
    type: float
    low: 0.00003
    high: 0.003
    log: true
  optimizer.weight_decay:
    type: float
    low: 0.0001
    high: 0.05
    log: true
  model.dropout:
    type: float
    low: 0.05
    high: 0.35
  model.shared_dim:
    type: categorical
    choices: [128, 192, 256, 320]
  model.graph_keep_mass:
    type: float
    low: 0.6
    high: 0.95
  model.protein_steps:
    type: int
    low: 2
    high: 4
  model.function_steps:
    type: int
    low: 1
    high: 3
  scheduler.warmup_epochs:
    type: int
    low: 1
    high: 8

constraints:
  max_parameters: 28000000
  max_gpu_memory_gb: 16

callbacks:
  prune_patience: 3
  min_epochs: 6
  checkpoint_metric: fmax