# @package _global_
# train_default.yaml
# baseline training schedule + logging knobs for PF-AGCN.

training:
  seed: 10
  max_epochs: 80
  gradient_clip: 1.0
  precision: 32
  accumulate_batches: 1
  log_interval: 50
  devices: 1
  accelerator: auto
  strategy: null
  deterministic: true
  enable_progress_bar: true
  limit_train_batches: null
  limit_val_batches: null
  fast_dev_run: false

optimizer:
  name: adamw
  lr: 0.0005
  weight_decay: 0.01
  betas: [0.9, 0.999]

scheduler:
  name: cosine
  warmup_epochs: 5
  min_lr: 0.000005

data:
  train_manifest: null
  val_manifest: null
  test_manifest: null
  batch_size: 8
  num_workers: 4
  pin_memory: true
  drop_last: false

evaluation:
  metric: fmax
  val_interval: 1
  threshold_grid: [0.1, 0.3, 0.5, 0.7]

